### ISSUE TITLE
Incorrect verified boot key fingerprint for OnePlus 7 Pro (GM1913)

### ISSUE THREAD

**Issue by jasperweiss** [GrapheneOS/AttestationSamples#1]
The verified boot key fingerprint included in the attestation app for the OnePlus 7 Pro does not seem to match that of 3 seperate devices I've tested. They all return the fingerprint listed in [this image](https://imgur.com/a/YDCaAxG).

The fingerprint (copied by hand) is: 4890D290DD5ACB722000603F9ED61BF2AEF5D0797AE0A
9F0B506405FD96C7AFB

**Comment by thestinger** [comment]
I'll look into this. It's possible that OnePlus deployed an update to the bootloader or TrustZone keymaster app causing the fingerprint to be calculated differently. I've seen this happen before on the Pixel 3 and 3 XL, but I have those devices and heavily test them so there was an update released to Auditor before anyone actually ran into this in the wild since I pushed it out before their OS update actually started being rolled out to regular users, due to staggered updates.

**Comment by thestinger** [comment]
@Bodup I've checked my existing samples and the current fingerprint appears to have been correct in the past. This fingerprint should never be able to change, but perhaps they altered the calculation like what happened with the Pixel 3. It would be helpful if you could submit new samples from devices that you have access to using the 'Submit sample data' option. I need to have valid samples with the new fingerprint to be able to change this, and it's still going to be problematic.
